export const TOGGLE_VENUE = 'TOGGLE_VENUE';

export const GET_CURRENT_GPS_LOCATION = 'GET_CURRENT_GPS_LOCATION';
export const GET_CURRENT_GPS_LOCATION_SUCCESS = 'GET_CURRENT_GPS_LOCATION_SUCESS';
export const GET_CURRENT_GPS_LOCATION_FAILED = 'GET_CURRENT_GPS_LOCATION_FAILED';

export const GET_VENUES = 'GET_VENUES';
export const GET_VENUES_SUCCESS = 'GET_VENUES_SUCCESS';
export const GET_VENUES_FAILED = 'GET_VENUES_FAILED';

export const CLOSE_VENUE_PANEL = 'CLOSE_VENUE_PANEL';

export const LOAD_VENUE_ITEM = 'LOAD_VENUE_ITEM';
export const LOAD_VENUE_ITEM_SUCCESS = 'LOAD_VENUE_ITEM_SUCCESS';
export const LOAD_VENUE_ITEM_FAILED = 'LOAD_VENUE_ITEM_FAILED';
