export const TOGGLE_VENUE = 'TOGGLE_VENUE';

export const GET_CURRENT_GPS_LOCATION = 'GET_CURRENT_GPS_LOCATION';
export const GET_CURRENT_GPS_LOCATION_SUCCESS = 'GET_CURRENT_GPS_LOCATION_SUCESS';
export const GET_CURRENT_GPS_LOCATION_FAILED = 'GET_CURRENT_GPS_LOCATION_FAILED';
